apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 167239449235.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    ports:
    - containerPort: 3306
  imagePullSecrets:
  - name: regcred