apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
  namespace: fp
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: mysql:8.0
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              echo "Waiting for MySQL..."
              until mysqladmin ping -h mysql -p"$MYSQL_ROOT_PASSWORD" --silent; do sleep 2; done
              echo "Creating DB/table..."
              mysql -h mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e "
                CREATE DATABASE IF NOT EXISTS employees;
                USE employees;
                CREATE TABLE IF NOT EXISTS employee (
                  emp_id INT PRIMARY KEY,
                  first_name VARCHAR(32),
                  last_name  VARCHAR(32),
                  primary_skill VARCHAR(64),
                  location VARCHAR(64)
                );
              "
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
