name: Build and Push to ECR

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push WebApp image
        run: |
          docker build -t webapp-repo ./webapp
          docker tag webapp-repo:latest ${{ steps.login-ecr.outputs.registry }}/webapp-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/webapp-repo:latest

      - name: Build and push MySQL image
        run: |
          docker build -t mysql-repo ./mysql-custom
          docker tag mysql-repo:latest ${{ steps.login-ecr.outputs.registry }}/mysql-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/mysql-repo:latest
